version: "3.9"

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_URL: http://frontend:3010
      DB_HOST: db
    volumes:
      - ../data:/app/data
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    volumes:
      - ../public:/app/public
    depends_on:
      - backend
    networks:
      - app

volumes:
  db_data:

networks:
  app: